WebApplication1/Models/IndividualContributor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class IndividualContributor
    {
        [Key]
        public int IndividualContributorId { get; set; }

        [Display(Name = "Nombre")]
        [StringLength(20, ErrorMessage = "Maximo 20 caracteres")]
        [Required(ErrorMessage = "Debes agregar un nombre")]
        public string Name { get; set; }

        [RegularExpression("[0-9]{4}\\-[0-9]{4}", ErrorMessage = "Debes digitar los primeros 4 digitos seguidos de un guion(-) y los ultimos 4 digitos")]
        [Display(Name = "Telefono", Prompt = "0000-0000")]
        [Required(ErrorMessage = "Debes agregar un numero de telefono")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Identificacion")]
        [Required(ErrorMessage = "Debes agregar un numero de identificacion")]
        public int Identification { get; set; }
        public byte[] PictureArray { get; set; }

        [Display(Name = "Correo")]
        [Required(ErrorMessage = "Debes agregar un correo")]
        [EmailAddress(ErrorMessage = "Direccion  de correo invalida")]
        public string Mail { get; set; }
        public ICollection<Article> Articles { get; set; }
    }
}

WebApplication1/Controllers/IndividualContributorsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class IndividualContributorsController : Controller
    {
        private WebApplication1Context db = new WebApplication1Context();

        // GET: IndividualContributors
        public ActionResult Index()
        {
            return View(db.IndividualContributors.ToList());
        }

        private void CreateUser(ApplicationDbContext db_user, IndividualContributor individualContributor)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db_user));
            var user = new ApplicationUser
            {
                UserName = individualContributor.Mail,
                Email = individualContributor.Mail
            };

            userManager.Create(user, "abcd1234.");

        }


        // GET: IndividualContributors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IndividualContributors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IndividualContributor individualContributor, string url)
        {
            if (ModelState.IsValid && url != null)
            {
                individualContributor.PictureArray = Convert.FromBase64String(url);
                db.IndividualContributors.Add(individualContributor);
                db.SaveChanges();
                ApplicationDbContext db_user = new ApplicationDbContext();
                CreateUser( db_user, individualContributor);

                return RedirectToAction("Index");
            }
            ViewBag.Url = url;
            return View(individualContributor);
        }

        // GET: IndividualContributors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IndividualContributor individualContributor = db.IndividualContributors.Find(id);
            if (individualContributor == null)
            {
                return HttpNotFound();
            }
            return View(individualContributor);
        }

        // POST: IndividualContributors/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IndividualContributorId,Name,PhoneNumber,Identification,Mail")] IndividualContributor individualContributor, string url)
        {
            if (ModelState.IsValid && url != null)
            {

                individualContributor.PictureArray = Convert.FromBase64String(url);
                db.Entry(individualContributor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(individualContributor);
        }

        // GET: IndividualContributors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IndividualContributor individualContributor = db.IndividualContributors.Find(id);
            if (individualContributor == null)
            {
                return HttpNotFound();
            }
            return View(individualContributor);
        }

        // POST: IndividualContributors/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IndividualContributor individualContributor = db.IndividualContributors.Find(id);
            db.IndividualContributors.Remove(individualContributor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/IndividualContributors/Create.cshtml
@model WebApplication1.Models.IndividualContributor

@{
    ViewBag.Title = "Create";
}

<div class="p-4">
    <div class="justify-content-center d-flex">
        <h3 class="url-label">Colaboradores</h3>
    </div>

    @using (Html.BeginForm("Create", "IndividualContributors", FormMethod.Post, new { enctype = "multipart/form-data", @id = "Form" }))
    {
        @Html.AntiForgeryToken()



        <div class="form-horizontal ">
            <h4>Agregar colaborador</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class="control-label col-md-2 p-0">Foto</label>
                <div class="col-md-12 d-flex flex-wrap ">
                    <div class="col-md-1 d-flex " style="min-width: 120px;">
                        <label for="pickImage" class="image-label-style mt-0  px-0" style="width:120px !important; height:120px; "><i class="fas fa-camera-retro fa-2x" style="color: gray;"></i></label>
                        <input id="pickImage" type="file" name="imageload" style="display: none" onchange="showPreview(event)" />
                    </div>
                    <div class="col-md-3 d-flex" id="imagePreview">
                        @if (ViewBag.Url != null)
                        {
                            <img class="thumbnail foto.jpg" src="data:image/jpeg;base64,@ViewBag.Url" id="foto.jpg">
                            <i id="foto.jpg" class="fas fa-times-circle close-button-style foto.jpg" aria-hidden="true"></i>
                            <input name="url" class="input" style="display: none;" id="foto.jpg" type="text" value="@ViewBag.Url">

                        }
                    </div>
                    <div class="col-md-12">
                        <span class="text-danger field-validation-error" id="ImageError">
                        </span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="button" onclick="formValidation()" value="Crear" class="btn btn-success my-2" />
                    <a href="/IndividualContributors" class="btn btn-outline-secondary">Regresar</a>
                </div>
            </div>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/PersonalScripts/ImageScripts/SingleImage.js"></script>

    <script>
        function formValidation() {

            if (ImageValidation()) {
                document.getElementById("Form").submit();
            }
        }
    </script>
}

WebApplication1/Views/IndividualContributors/Delete.cshtml
@model WebApplication1.Models.IndividualContributor

@{
    ViewBag.Title = "Delete";
}

<div class="p-4">
    <div class="justify-content-center d-flex">
        <h3 class="url-label">Colaboradores</h3>
    </div>

    <div>
        <hr />
        <div class="justify-content-center d-flex text-center ">
            <div>
                <h5>
                    Si eliminas este colaborador no sera posible recuperarlo.
                </h5>
            </div>
        </div>
        <hr />



        <div class="justify-content-center d-flex flex-wrap  text-center">
            <div class="col-md-2 ">
                @{
                    var base64 = Convert.ToBase64String(Model.PictureArray);
                    var imgSrc = String.Format("data:image/png;base64,{0}", base64);

                    <img class="rounded-circle" src="@imgSrc" style="width:90px; height: 90px;">
                }

            </div>
            <div class="col-md-2 icAlignStyle">
                @Html.DisplayFor(modelItem => Model.Name)
            </div>
            <div class="col-md-2 icAlignStyle">
                @Html.DisplayFor(modelItem => Model.PhoneNumber)
            </div>
            <div class="col-md-2 icAlignStyle">
                @Html.DisplayFor(modelItem => Model.Identification)
            </div>
            <div class="col-md-2 icAlignStyle">
                @Html.DisplayFor(modelItem => Model.Mail)
            </div>
        </div>

        <hr />
        <div class="justify-content-center d-flex text-center">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Borrar" class="btn btn-danger" />
                    <a href="/IndividualContributors" class="btn btn-outline-secondary">Regresar</a>
                </div>
            }
        </div>
    </div>
</div>

WebApplication1/Views/IndividualContributors/Edit.cshtml
@model WebApplication1.Models.IndividualContributor

@{
    ViewBag.Title = "Edit";
}
    <div class="p-4">
        <div class="justify-content-center d-flex">
            <h3 class="url-label">Colaboradores</h3>
        </div>

        @using (Html.BeginForm("Edit", "IndividualContributors", FormMethod.Post, new { enctype = "multipart/form-data", @id = "Form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal ">
                <h4>Editar colaborador</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IndividualContributorId)

                <div class="form-group">
                    <label class="control-label col-md-2 p-0">Foto</label>
                    <div class="col-md-12 d-flex flex-wrap ">
                        <div class="col-md-1 d-flex" style="min-width: 120px;">
                            <label for="pickImage" class="image-label-style mt-0 px-0" style="width:120px !important; height:120px;"><i class="fas fa-camera-retro fa-2x" style="color: gray;"></i></label>
                            <input id="pickImage" type="file" name="imageload" style="display: none" onchange="showPreview(event)" />
                        </div>
                        <div class="col-md-3 d-flex" id="imagePreview">
                            @{
                                var base64 = Convert.ToBase64String(Model.PictureArray);
                                var imgSrc = String.Format("data:image/jpeg;base64,{0}", base64);

                            }
                            <img class="thumbnail foto.jpg" src="@imgSrc" id="foto.jpg">
                            <i id="foto.jpg" class="fas fa-times-circle close-button-style foto.jpg" aria-hidden="true"></i>
                            <input name="url" class="input" style="display: none;" id="foto.jpg" type="text" value="@base64">

                        </div>
                        <div class="col-md-12">
                            <span class="text-danger field-validation-error" id="ImageError">
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Identification, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Identification, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Identification, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" onclick="formValidation()" value="Guardar cambios" class="btn btn-success my-2" />
                        <a href="/IndividualContributors" class="btn btn-outline-secondary">Regresar</a>
                    </div>
                </div>
            </div>
        }
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/PersonalScripts/ImageScripts/SingleImage.js"></script>
    <script>
        function formValidation() {

            if (ImageValidation()) {
                document.getElementById("Form").submit();
            }
        }
    </script>

}

WebApplication1/Views/IndividualContributors/Index.cshtml
@model IEnumerable<WebApplication1.Models.IndividualContributor>

@{
    ViewBag.Title = "Index";
}

<div class="p-4">
    <div class="justify-content-center d-flex">
        <h3 class="url-label">Colaboradores</h3>
    </div>

    <div class="d-flex mb-2">
        @Html.ActionLink("Agregar", "Create", null, new { @class = "btn btn-outline-primary" })
    </div>
    <hr />



    @foreach (var item in Model)
    {
        <div class="container d-flex flex-wrap mb-3 p-2 text-center justify-content-center ">

            <div class="col-md-2 ">
                @{
                    var base64 = Convert.ToBase64String(item.PictureArray);
                    var imgSrc = String.Format("data:image/png;base64,{0}", base64);

                    <img class="rounded-circle" src="@imgSrc" style="width:90px; height: 90px;">
                }

            </div>
            <div class="col-md-2 icAlignStyle">
                @Html.DisplayFor(modelItem => item.Name)
            </div>
            <div class="col-md-2 icAlignStyle">
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </div>
            <div class="col-md-3 icAlignStyle text-break">
                @Html.DisplayFor(modelItem => item.Mail)
            </div>
            <div class="col-md-3 icAlignStyle justify-content-center d-flex ">
                @Html.ActionLink("Editar", "Edit", new { id = item.IndividualContributorId }, new { @class = "btn btn-outline-info" })
                @*@Html.ActionLink("Borrar", "Delete", new { id = item.IndividualContributorId }, new { @class = "btn btn-outline-danger delete-button" })*@

            </div>
        </div>
        <hr />
    }

</div>