WebApplication1/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Http.ModelBinding;

namespace WebApplication1.Models
{
    public class Client
    {
        [Key]
        public int ClientId { get; set; }

        public DateTime Join { get; set; }

        [Display(Name = "Nombre")]
        [StringLength(20, ErrorMessage = "Maximo 20 caracteres")]
        [Required(ErrorMessage = "Debes agregar un nombre")]
        public string Name { get; set; }

        [Display(Name = "Correo")]
        [Required(ErrorMessage = "Debes agregar un correo")]
        [EmailAddress(ErrorMessage = "Direccion  de correo invalida")]
        public string Mail { get; set; }

        [RegularExpression("[0-9]{4}\\-[0-9]{4}", ErrorMessage = "Debes digitar los primeros 4 digitos seguidos de un guion(-) y los ultimos 4 digitos")]
        [Display(Name = "Telefono", Prompt = "0000-0000")]
        [Required(ErrorMessage = "Debes agregar un numero de telefono")]
        public string PhoneNumber { get; set; }

        public int UbicationCategory { get; set; }

        public int RangeFrom { get; set; }

        public int RangeTo { get; set; }

        public ICollection<ArticleClient> ArticlesClient { get; set; }

        public ICollection<ClientStateAction> clientStateActions { get; set; }


    }
}

WebApplication1/Models/StateActions.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace WebApplication1.Models
{
    public class StateAction
    {
        [Key]
        public int StateActionId { get; set; }

        public string Name { get; set; }

        public int? WaitTime { get; set; }

        public ICollection<StateActionState> StateActionStates { get; set; }
    }
}

WebApplication1/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ClientsController : Controller
    {
        private WebApplication1Context db = new WebApplication1Context();

        // GET: Clients
        public ActionResult Index()
        {
            ViewBag.CLientStateAction = db.ClientStateAction.ToList();

            return View(db.Clients.ToList());
        }



        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientId,Name,Mail,PhoneNumber")] Client client)
        {


            if (ModelState.IsValid)
            {
                db.Clients.Add(client);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }

            ViewBag.States = db.ClientStates.ToList();
            ViewBag.Actions = db.StateActions.ToList();
            ViewBag.ActionStates = db.StateActionState.ToList();
            var clientState = from c in db.ClientStateAction
                              where c.ClientId == id
                              select c;

            ViewBag.CLientStateAction = clientState.ToList();
            List<int> InState = new List<int>();
            foreach (var ClientState in clientState.ToList())
            {
                StateActionState stateActionState = db.StateActionState.Find(ClientState.StateActionStateId);
                InState.Add(stateActionState.ClientStateId);
            }

            ViewBag.ActualState = InState.Max();

            return View(client);
        }

        public ActionResult AddAction(int StateActionStateId, int ClientId, string Message)
        {


            ClientStateAction clientStateAction = StateKey(ClientId, Message, StateActionStateId);
            if (clientStateAction == null)
            {
                clientStateAction = CreateClientStateAction(ClientId, Message, StateActionStateId);
            }

            db.ClientStateAction.Add(clientStateAction);
            db.SaveChanges();
            ViewBag.States = db.ClientStates.ToList();
            ViewBag.Actions = db.StateActions.ToList();
            ViewBag.ActionStates = db.StateActionState.ToList();
            var clientState = from c in db.ClientStateAction
                              where c.ClientId == ClientId
                              select c;
            ViewBag.CLientStateAction = clientState.ToList();
            List<int> InState = new List<int>();
            foreach (var ClientState in clientState.ToList())
            {
                StateActionState stateActionState = db.StateActionState.Find(ClientState.StateActionStateId);
                InState.Add(stateActionState.ClientStateId);
            }
            ViewBag.ActualState = InState.Max();

            return PartialView("StateView");
        }

        public ClientStateAction StateKey(int ClientId, string Message, int StateActionStateId)
        {
            ClientStateAction clientStateAction = null;

            StateActionState stateActionState = db.StateActionState.FirstOrDefault(s => s.StateActionStateId == StateActionStateId);
            StateAction action = db.StateActions.FirstOrDefault(x => x.StateActionId == stateActionState.StateActionId);

            StateActionState NewStateActionState;

            if (action.Name == "Rechazado")
            {
                NewStateActionState = db.StateActionState.FirstOrDefault(
                    s => s.ClientState.Name == "Rechazado" && s.StateAction.Name == "Rechazado");
                clientStateAction = CreateClientStateAction(ClientId, Message, NewStateActionState.StateActionStateId);
            }

            switch (stateActionState.ClientState.Name)
            {
                case "Lead":
                    if (action.Name == "Llamada")
                    {
                        NewStateActionState = db.StateActionState.FirstOrDefault(
                           s => s.ClientState.Name == "Contacto" && s.StateAction.Name == "llamada");
                        clientStateAction = CreateClientStateAction(ClientId, Message, NewStateActionState.StateActionStateId);
                    }
                    break;
                case "Contacto":
                    if (action.Name == "Cita")
                    {
                        NewStateActionState = db.StateActionState.FirstOrDefault(
                           s => s.ClientState.Name == "Visita" && s.StateAction.Name == "Cita");
                        clientStateAction = CreateClientStateAction(ClientId, Message, NewStateActionState.StateActionStateId);
                    }
                    break;
                case "Visita":
                    if (action.Name == "Venta realizada")
                    {
                        NewStateActionState = db.StateActionState.FirstOrDefault(
                           s => s.ClientState.Name == "Venta" && s.StateAction.Name == "Venta realizada");
                        clientStateAction = CreateClientStateAction(ClientId, Message, NewStateActionState.StateActionStateId);
                    }
                    break;
                case "Venta":
                    if (action.Name == "Cerrar")
                    {
                        NewStateActionState = db.StateActionState.FirstOrDefault(
                           s => s.ClientState.Name == "Vendido" && s.StateAction.Name == "Venta realizada");
                        clientStateAction = CreateClientStateAction(ClientId, Message, NewStateActionState.StateActionStateId);
                    }
                    break;
                case "Rechazado":
                    if (action.Name == "Recuperar cliente")
                    {
                        ClientStateAction clientStateActionToDelete = db.ClientStateAction.FirstOrDefault(
                            c => c.ClientId == ClientId && c.StateActionState.ClientState.Name == "Rechazado");
                        db.ClientStateAction.Remove(clientStateActionToDelete);
                        db.SaveChanges();
                        NewStateActionState = db.StateActionState.FirstOrDefault(
                           s => s.ClientState.Name == "Contacto" && s.StateAction.Name == "Informacion");
                        clientStateAction = CreateClientStateAction(ClientId, Message, NewStateActionState.StateActionStateId);
                    }
                    break;
                default:
                    clientStateAction = null;
                    break;
            }

            return clientStateAction;

        }

        public ClientStateAction CreateClientStateAction(int ClientId, string Message, int StateActionStateId)
        {
            ClientStateAction clientStateAction = new ClientStateAction();
            clientStateAction.ClientId = ClientId;
            clientStateAction.JoinAction = DateTime.Now;
            clientStateAction.Message = Message;
            clientStateAction.StateActionStateId = StateActionStateId;

            return clientStateAction;
        }

        // POST: Clients/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientId,Name,Mail,PhoneNumber")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Clients/Create.cshtml
@model WebApplication1.Models.Client

@{
    ViewBag.Title = "Create";
}

    <div class="justify-content-center d-flex">
        <h3 class="url-label">Clientes</h3>
    </div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Agregar cliente</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { Placeholder = "Example@Host.com", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { Placeholder = "0000-0000", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-success" />
            <a href="/Clients" class="btn btn-outline-secondary">Regresar</a>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Clients/Delete.cshtml
@model WebApplication1.Models.Client

@{
    ViewBag.Title = "Delete";
}

<div class="p-4">
    <div class="justify-content-center d-flex">
        <h3 class="url-label">Clientes</h3>
    </div>

    <div>
        <hr />
        <div class="justify-content-center d-flex text-center">
            <div>
                <h5>
                    Si eliminas este cliente no sera posible recuperarlo.
                </h5>
            </div>
        </div>
        <hr />

        <div class="justify-content-center d-flex text-center">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Mail)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Mail)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>

            </dl>
        </div>

        <div class="justify-content-center d-flex">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Borrar" class="btn btn-danger" />
                    <a href="/Clients" class="btn btn-outline-secondary">Regresar</a>
                </div>
            }
        </div>
    </div>
</div>

WebApplication1/Views/Clients/Edit.cshtml
@model WebApplication1.Models.Client

@{
    ViewBag.Title = "Edit";
}

<div class="p-4">

    <div class="justify-content-center d-flex">
        <h3 class="url-label">Clientes</h3>
    </div>
    <div class="d-flex flex-wrap">
        @using (Html.BeginForm("Edit", "Clients", FormMethod.Post, new { @class = "col-md-6" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <h4>Editar cliente</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ClientId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        }
        <div class="col-md-6" id="states">
            @Html.Partial("StateView")
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar cambios" class="btn btn-success m-2" />
                <a href="/Clients" class="btn btn-outline-secondary m-2">Regresar</a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ActionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Agregar accion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group d-flex justify-content-center">
                        <label class="control-label col-12"><strong>Introduzca un mensaje para la accion</strong></label>
                        <textarea class="form-control" aria-label="With textarea" rows="6" cols="50" id="message"></textarea>
                    </div>
                    <input class="d-none" id="Action_ClientId" value="@Model.ClientId" />
                    <input class="d-none" id="Action_StateAction" value="" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="button" onclick="SendForm()" class="btn btn-primary">Agregar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="Bitacora" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Bitacora</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group d-flex justify-content-center">
                        <table class="table mt-3 text-center">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Accion</th>
                                    <th scope="col">Mensaje</th>
                                    <th scope="col">Fecha</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var client in ViewBag.CLientStateAction)
                                {
                                    <tr>
                                        <td>
                                            @client.StateActionState.StateAction.Name
                                        </td>
                                        <td>
                                            @client.Message
                                        </td>
                                        <td>
                                            @client.JoinAction
                                        </td>
                                    </tr>

                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div class="modal p-0" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="background-color: rgba( 255, 255, 255, .5)">
    <div class="modal-dialog load-gif m-0" role="document">
        <div class="modal-content load-gif bg-transparent">
            <img class="house-gif" src="~/Images/home-solid.svg" height="100" id="house-gif" />

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    function AddAction(StateActionStateId) {
        var element = document.getElementById("Action_StateAction");
        element.value = StateActionStateId;
        $("#ActionModal").modal("show");
    }

        function SendForm() {
        $('#exampleModal').modal('show');

        var StateActionStateId = document.getElementById("Action_StateAction").value;
        var ClientId = document.getElementById("Action_ClientId").value;
        var message = document.getElementById("message").value;

            $.ajax({
                type: "POST",
                url: '@Url.Action("AddAction","Clients")',
                data: {
                    StateActionStateId: StateActionStateId,
                    ClientId: ClientId,
                    Message: message

                },
                cache: false
            })
                .then(function (data) {
                    var container = document.getElementById("states");
                    container.innerHTML = data;
                    $("#ActionModal").modal("hide");
                    document.getElementById("message").innerHTML = "";
                            $('#exampleModal').modal('hide');


                })
                .fail(function (data) {
                            $('#exampleModal').modal('hide');

                })
               return false;
    }
    </script>

}

WebApplication1/Views/Clients/Index.cshtml
@model IEnumerable<WebApplication1.Models.Client>

@{
    ViewBag.Title = "Index";
}
<div class="p-4">

    <div class="justify-content-center d-flex">
        <h3 class="url-label">Clientes</h3>
    </div>

    <div class="d-flex mb-2">
        @*@Html.ActionLink("Agregar", "Create", null, new { @class = "btn btn-outline-primary" })*@
    </div>
    <hr />



    <div class="container-fluid d-flex flex-wrap p-2 justify-content-center">

        @foreach (var item in Model)
        {
            var actualState = 1;
            var stateName = "Lead";

            <div class="col-md-3 d-flex m-2 flex-wrap p-0  text-center  border-secondary rounded text-center shadow-lg">
                <div class="col-md-12 p-2 text-white" style="background-color: rgba(0,0,0,.6);">
                    <strong>
                        @Html.DisplayFor(modelItem => item.Name)
                    </strong>
                </div>
                <div class="col-md-12 p-2 text-break">
                    @Html.DisplayFor(modelItem => item.Mail)
                </div>
                <div class="col-md-12 p-2">
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </div>
                <div class="col-md-12 p-2">
                    @foreach (var state in ViewBag.CLientStateAction)
                    {
                        if (item.ClientId == state.ClientId && state.StateActionState.ClientStateId > actualState)
                        {
                            stateName = state.StateActionState.ClientState.Name;
                        }
                    }
                    <label><strong>@stateName</strong></label>

                </div>

                <div class="col-md-12 d-flex p-4 flex-wrap justify-content-center ">
                    @Html.ActionLink("Editar", "Edit", new { id = item.ClientId }, new { @class = "btn btn-outline-info" })
                    @Html.ActionLink("Borrar", "Delete", new { id = item.ClientId }, new { @class = "btn btn-outline-danger delete-button" })
                </div>
            </div>
        }
    </div>
</div>

WebApplication1/Views/Clients/StateView.cshtml
@model WebApplication1.Models.Client


<h4>Seguimiento</h4>
<hr />
<div class="form-group">
    <div class="col-md-12 d-flex flex-wrap justify-content-center">
        @foreach (var state in ViewBag.States)
        {
            if (state.ClientStateId == ViewBag.ActualState)
            {
                <label class="col-12">Estado actual: <strong>@state.Name</strong></label>
                <select class="form-control m-2" onchange='AddAction(this.value)'>
                    <option selected disabled>Agregar accion</option>

                    @foreach (var ActionState in state.StateActionState)
                    {
                        var content = ActionState.StateAction.WaitTime > 0 ? ActionState.StateAction.Name + " " + ActionState.StateAction.WaitTime + " dias" : ActionState.StateAction.Name;
                        <option class="col-12" value="@ActionState.StateActionStateId">@content</option>
                    }
                </select>
                <button type="button" class="btn btn-success m-2" data-toggle="modal" data-target="#Bitacora">
                    Bitacora
                </button>
                <table class="table mt-3 text-center">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Accion</th>
                            <th scope="col">Mensaje</th>
                            <th scope="col">Fecha de accion</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var client in ViewBag.CLientStateAction)
                        {
                            if (client.StateActionState.ClientStateId == state.ClientStateId)
                            {

                                <tr>
                                    <td>
                                        @client.StateActionState.StateAction.Name
                                    </td>
                                    <td>
                                        @client.Message
                                    </td>
                                    <td>
                                        @client.JoinAction
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            }
        }
    </div>
</div>