WebApplication1/Models/Article.cs
using Microsoft.VisualBasic.ApplicationServices;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Models
{
    public class Article
    {
        public int Id { get; set; }

        [Display(Name = "Descripcion")]
        public string Description { get; set; }

        [Display(Name = "Propietario")]
        public string OwnerName { get; set; }

        [Display(Name = "Contacto propietario")]
        public int OwnerPhone { get; set; }

        [Display(Name = "Estado")]
        public bool State { get; set; }

        public DateTime CreationDate { get; set; }

        public EArticleKind ArticleKind { get; set; }
        public bool SoldState { get; set; }

        [Display(Name = "Codigo de articulo")]
        public string Code { get; set; }

        public string Currency { get; set; }

        [Display(Name = "Precio")]
        [Required(ErrorMessage = "Debes agregar un precio")]
        public string Price { get; set; }
        public virtual Terrain Terrain { get; set; }
        public int TerrainId { get; set; }
        public virtual Ubication Ubication { get; set; }
        public int UbicationId { get; set; }
        public virtual IndividualContributor IndividualContributor { get; set; }
        public int IndividualContributorId { get; set; }
        public ICollection<ArticleClient> ArticlesClient { get; set; }
        public ICollection<ArticlePicture> ArticlesPicture { get; set; }


        public int RefreshApproves()
        {
            using (WebApplication1Context db = new WebApplication1Context())
            {
                var rejects = db.Rejects.ToList();

                var approves = from a in db.Articles
                               where !a.State
                               select a;

                var result = approves.ToList().Count() - rejects.Count();

                return result;
            }
        }

        public int RefreshRejects(string userMail)
        {
            using (WebApplication1Context db = new WebApplication1Context())
            {
                var rejects = from r in db.Rejects
                              where r.Article.IndividualContributor.Mail == userMail
                              select r;
                var rejectsList = rejects.ToList();
                var result = rejects.Count();

                return result;
            }
        }
    }
}

WebApplication1/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Blog
    {
        [Key]
        public int BlogId { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public byte CoverImageArray { get; set; }

        public byte VideoArray { get; set; }
    }
}

WebApplication1/Controllers/ArticlesController.cs
using Microsoft.Azure;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.Script.Serialization;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "Create")]

    public class ArticlesController : Controller
    {
        public WebApplication1Context db = new WebApplication1Context();

        // GET: Articles
        public ActionResult Index()
        {

            List<ArticleViewModel> ArticleViewModelList = GetArticleViewModelList();
            ViewBag.ArticleKindId = EnumHelper.GetSelectList(typeof(EArticleKind));
            List<ArticleViewModel> NewArticleViewModelList = new List<ArticleViewModel>();

            foreach (var item in ArticleViewModelList.ToList())
            {
                if (item != null )
                {
                    NewArticleViewModelList.Add(item);
                }
            }
            return View(NewArticleViewModelList.ToList());
        }

        // GET: Articles/Create
        public ActionResult Create()
        {
            ViewBag.houseForm = "none";
            ViewBag.houseAuxForm = "none";
            ViewBag.TerrainId = new SelectList(db.Terrains.ToList(), "TerrainId", "Topography");
            ViewBag.UbicationId = new SelectList(db.Ubications.ToList(), "UbicationId", "Name");
            return View();
        }

        // POST: Articles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleViewModel articleViewModel, string[] urls, int[] Article_TerrainFeatures, string outstandingPicture, int[] Article_HouseFeatures,
            int[] Article_HouseAuxFeatures)
        {
            //HttpFileCollectionBase files = Request.Files;


            if (articleViewModel.Article != null && articleViewModel.Article.Terrain != null && urls.Length > 0
                && Article_TerrainFeatures.Length > 0 && outstandingPicture != null)
            {
                Article article = articleViewModel.Article;
                Terrain terrain = article.Terrain;

                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        try
                        {
                            db.Terrains.Add(terrain);
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            ViewBag.error = "Error al añadir terreno" + ex.InnerException;
                            return View("ErrorPage");
                        }

                        try
                        {
                            IndividualContributor individualContributor = db.IndividualContributors.FirstOrDefault(i => i.Mail == User.Identity.Name);
                            article.IndividualContributorId = individualContributor.IndividualContributorId;
                            article.Code = "A" + terrain.TerrainId;
                            article.State = false;
                            article.TerrainId = terrain.TerrainId;
                            article.SoldState = false;
                            article.CreationDate = DateTime.Now;
                            article.ArticleKind = EArticleKind.Venta;
                            db.Articles.Add(article);
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {
                            ViewBag.error = "Error al añadir casa" + ex.InnerException;
                            return View("ErrorPage");

                        }



                        AddTerrainFeatures(Article_TerrainFeatures, terrain.TerrainId);


                        //for (int i = 0; i < files.Count; i++)
                        //{
                        //    HttpPostedFileBase file = files[i];
                        //    if (file != null)
                        //    {
                        //        SubirArchivo(file, article.Id);
                        //    }
                        //}

                        try
                        {
                            List<ArticlePicture> Pictures = new List<ArticlePicture>();
                            ArticlePicture picture = new ArticlePicture();
                            picture.OutstandingPicture = true;
                            picture.Extension = AddBlobToStorage(article.Id, outstandingPicture, 20);
                            picture.ArticleId = article.Id;
                            Pictures.Add(picture);

                            var i = 0;
                            foreach (var url in urls)
                            {
                                picture = new ArticlePicture();
                                picture.OutstandingPicture = false;
                                picture.Extension = AddBlobToStorage(article.Id, url, i);
                                picture.ArticleId = article.Id;
                                Pictures.Add(picture);
                                i++;
                            }


                            db.ArticlePictures.AddRange(Pictures);
                            db.SaveChanges();
                        }
                        catch (Exception ex)
                        {

                            ViewBag.error = "Error al añadir fotos" + ex.InnerException;
                            return View("ErrorPage");

                        }



                        if (articleViewModel.House.HouseForeheadMeasure > 0 && articleViewModel.House.HouseBackgroundMeasure > 0)
                        {
                            AddHouse(articleViewModel.House, Article_HouseFeatures, article.Id);
                        }

                        if (articleViewModel.HouseAux.HouseForeheadMeasureAux > 0 && articleViewModel.HouseAux.HouseBackgroundMeasureAux > 0)
                        {
                            HouseAux houseAux = articleViewModel.HouseAux;
                            House house = new House();
                            house.Bathrooms = houseAux.BathroomsAux;
                            house.Bedrooms = houseAux.BedroomsAux;
                            house.Garage = houseAux.GarageAux;
                            house.HouseBackgroundMeasure = houseAux.HouseBackgroundMeasureAux;
                            house.HouseForeheadMeasure = houseAux.HouseForeheadMeasureAux;
                            house.Levels = houseAux.LevelsAux;
                            AddHouse(house, Article_HouseAuxFeatures, article.Id);
                        }


                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Index");
                    }

                    catch (Exception ex)
                    {
                        ViewBag.houseForm = "none";
                        ViewBag.houseAuxForm = "none";
                        ViewBag.IndividualContributorId = new SelectList(db.IndividualContributors, "IndividualContributorId", "Name");
                        ViewBag.TerrainId = new SelectList(db.Terrains, "TerrainId", "Topography");
                        ViewBag.UbicationId = new SelectList(db.Ubications, "UbicationId", "Name");
                        transaction.Rollback();
                        ReloadViewBags(articleViewModel);
                        ViewBag.error = ex.InnerException;
                        return View(articleViewModel);
                    }
                }
            }
            ReloadViewBags(articleViewModel);
            return View(articleViewModel);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                ViewBag.error = "El id no es valido";
                return View("ErrorPage");
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                ViewBag.error = "El articulo no existe";
                return View("ErrorPage");
            }

            Reject reject = db.Rejects.FirstOrDefault(r => r.ArticleId == id);

            if (reject != null)
            {
                ViewBag.error = reject.Reason;

            }

            //var filesEF = from f in db.Archivos
            //              where f.ArticleId == id
            //              select f;
            //ViewBag.Files = filesEF.ToList();
            ArticleViewModel articleViewModel = GetArticleViewModel(article);
            ReloadViewBags(articleViewModel);
            return View(articleViewModel);
        }

        // POST: Articles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleViewModel articleViewModel, string[] urls, int[] Article_TerrainFeatures, string outstandingPicture, int[] Article_HouseFeatures,
            int[] Article_HouseAuxFeatures)
        {
            Article article = db.Articles.Find(articleViewModel.Article.Id);

            HttpFileCollectionBase files = Request.Files;
            using (var transaction = db.Database.BeginTransaction())
            {

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Agents.cshtml
@model WebApplication1.Models.LandingView


<div class="col-12  text-center mb-3 d-flex flex-wrap justify-content-center align-items-center ">
    <h2 class="index-items-title text-dark m-4 col-12">
        Nuestros agentes
    </h2>
    <p class="agents-description">
        La meta de cualquiera de nuestros asesores siempre será conseguir la propiedad que usted necesita, al precio más cómodo del mercado y con la asesoría y respaldo que nos caracteriza.
    </p>
</div>

@{ 
            var i = 1;

}

<div class="container-fluid p-3 d-flex flex-wrap  justify-content-center">

    @foreach (var item in Model.IndividualContributors)
    {
        var imgSrc = String.Format("data:image/png;base64,{0}", Convert.ToBase64String(item.PictureArray));

    <div class="col-md-4 d-flex flex-wrap ic ic-@i">
        <div class="col-md-12 ic-shadow" >

        </div>
        <div class="col-md-12 p-0 d-flex justify-content-center ic-picture-container mb-5">
            <div class="rounded-circle ic-picture-img">
                <img src="@imgSrc" alt="Alternate Text" style="width: inherit; height: inherit;"/>
            </div>
        </div>


        <div class="container flex-wrap d-flex justify-content-center text-center p-2 ic-info-container">

            <div class="col-md-12 p-2 d-flex justify-content-center">
                <h4>
                    <strong class="">
                        @item.Name
                    </strong>
                </h4>
            </div>

            <div class="col-md-12 p-2 d-flex justify-content-center">
                <h5>
                    <strong class="index-item-price">
                        @item.PhoneNumber
                    </strong>
                </h5>
            </div>

            <div class="col-md-12 p-2 d-flex justify-content-center ic-mail">
                <p>
                    @item.Mail
                </p>
            </div>
        </div>
    </div>

        if (i == 3)
        {
            i = 1;
        }
                i++;

    }

</div>

WebApplication1/Views/Home/Blog.cshtml
@model WebApplication1.Models.Blog

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/ErrorPage.cshtml
@{
    ViewBag.Title = "ErrorPage";
}

<div class="d-flex justify-content-center align-items-center flex-wrap align-content-center bg-white" style="height: 100vh; max-width: 100vw;">
    <div class="col-12 d-flex justify-content-center">
        <img src="https://speoimages.blob.core.windows.net/commonimages/logo2.png" alt="" height="400" width="300"/>
    </div>
    <div class="col-12 text-center ">  
        <strong>Felicidades!!!</strong>
        <p>Acabas de encontrar un error, para reportarlo envia una imagen de esta pantalla.</p>
        <small>@ViewBag.error</small>
    </div>
</div>

WebApplication1/Views/Home/PropertiesView.cshtml
@model IEnumerable<WebApplication1.ViewModel.ArticleViewModel>

@{
    ViewBag.Title = "PropertiesView";
}
<div class="bg-dark position-relative position-fixed" style="z-index:15; width: 100vw; top: 0; z-index:100;">
    <nav class="navbar navbar-expand-lg navbar-dark nav-style mb-0">
        <div class="d-flex justify-content-center align-content-center">
            <div class="bg-light background-brand"></div>
            <a href="/" class="brand">

                <img class="brand" src="~/Images/logo2.png" />
            </a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse  navbar-collapse-style" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link label-brand" href="/">SU PROPIEDAD EN OCCIDENTE <span class="sr-only">(current)</span></a>
                </li>
                @if (User.IsInRole("Create"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ubicaciones
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Cantones", "Index", "Cantons", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Distritos", "Index", "Distrits", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Categorias de ubicacion", "Index", "UbicationCategories", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Caracteristicas de ubicacion", "Index", "UbicationFeatures", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Ubicaciones", "Index", "Ubications", null, new { @class = "dropdown-item" })

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Personas
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Clientes", "Index", "Clients", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Colaboradores", "Index", "IndividualContributors", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Articulos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Caracteristicas de terreno", "Index", "TerrainFeatures", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Caracteristicas de casa", "Index", "HouseFeatures", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Articulos", "Index", "Articles", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Seguridad
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("Roles", "Index", "Users", null, new { @class = "dropdown-item" })
                                @Html.ActionLink("Aprobaciones", "ApproveArticles", "Articles", null, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                }

            </ul>
            <div>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
</div>

<div class="container-fluid d-flex properties-filter flex-wrap justify-content-center py-3">

    <div class="col-md-3 text-light d-flex flex-nowrap justify-content-center">
        <div class="col-12 mb-2 justify-content-center d-flex ">
            <select class="form-control filter-element" style="font-size: 15px !important;" id="type" onchange="getParamsList(this.value)">
                <option selected disabled value="0" >Filtrar por</option>
                <option value="Ubicacion">Ubicacion</option>
                <option value="Categoria">Categoria</option>
                <option value="Tamaño">Tamaño</option>
                <option value="Precio">Precio</option>
            </select>
        </div>
    </div>

    <div class="col-md-3 flex-nowrap justify-content-center text-center " style="display: none;" id="currency">
        <div class="col-12 mb-2 justify-content-center d-flex ">
            <select class="form-control filter-element" style="font-size: 15px !important;" onchange="GetPrices(this.value)">
                <option selected disabled value="0">Moneda</option>
                <option value="¢">¢ - Colones</option>
                <option value="$">$ - Dolares</option>
            </select>
        </div>
    </div>

    <div class="col-md-3 text-light d-flex flex-nowrap justify-content-center">
        <div class="col-12 mb-2 justify-content-center d-flex ">
            <select class="form-control filter-element" style="font-size: 15px !important;" id="option" onchange="Filter(false)">
                <option selected disabled value="0">Opciones</option>
            </select>
        </div>
    </div>

    <div class="col-md-3  d-flex flex-wrap justify-content-center " style="align-content: flex-end;">
        <div class="mb-2">
            <button class="btn btn-danger filter-element" type="button" style="font-size: 15px !important;" onclick="Filter(true)">
                Reiniciar filtro
            </button>
        </div>
    </div>
</div>

<div class="p-1">

    <div class=" d-flex justify-content-center properties-head">
        <img class="rounded" src="~/Images/logo2.png" style="height:100px;" />
    </div>
    <div class="justify-content-center text-center p-4 d-flex">
        <h5>
            Tenemos mas de 500 propiedades a tu disposicion.
            <br />
            Vamos a verlas!!!
        </h5>
    </div>

    <div class="container-fluid p-0 flex-wrap d-flex justify-content-center ">

        <div class="d-flex flex-wrap col-12" id="articleListContainer">
            @Html.Partial("ArticleList")
        </div>
    </div>

</div>

<div class="modal p-0" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="background-color: rgba( 255, 255, 255, .5)">
    <div class="modal-dialog load-gif m-0" role="document">
        <div class="modal-content load-gif bg-transparent">
            <img class="house-gif" src="~/Images/home-solid.svg" height="100" id="house-gif" />

        </div>
    </div>
</div>

<script>

    function getParams(paramsList) {
            document.getElementById("option").innerHTML = paramsList;
    }

    function GetSizes() {

        var content =
            `<option selected disabled value="0">Seleccionar tamaño</option>
              <option value="1">100mts - 300mts</option>
             <option value="2">300mts - 500mts</option>
             <option value="3">500mts - 700mts</option>
             <option value="4">700mts - En adelante</option>`

        document.getElementById("option").innerHTML = content;

    }

    function GetPrices(currency) {
                $('#exampleModal').modal('show');

        var content = "";
        if (currency == "$") {
             content =
            `<option selected disabled value="0">Seleccionar moneda</option>
             <option value="1">$20,000 - $30,000</option>
             <option value="2">$30,000 - $40,000</option>
             <option value="3">$40,000 - En adelante</option>`
        }
        else {
            content =
            `<option selected disabled value="0">Seleccionar monto</option>
             <option value="4">¢10,000,000 - ¢20,000,000</option>
             <option value="5">¢20,000,000 - ¢30,000,000</option>
             <option value="6">¢30,000,000 - En adelante</option>`
        }

        document.getElementById("option").innerHTML = content;
                $('#exampleModal').modal('hide');

    }

    function getParamsList(type) {
            $('#exampleModal').modal('show');

        document.getElementById("currency").style.display = "none";

        switch (type) {

            case "Precio":
                document.getElementById("currency").style.display = "block";
                break;
            case "Tamaño":
                GetSizes();
                break;

            default:
                 $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetParamsList","Home")',
                    data: {
                        type: type
                    },
                    cache: false
                })
                    .then(function (data) {
                        getParams(data);
                                        $('#exampleModal').modal('hide');

                    })
                    .fail(function (data) {
                        alert('No hay caracteristicas que mostrar!');
                    })

                return false;
        }

                $('#exampleModal').modal('hide');

    }

    function Filter(clean) {
        $('#exampleModal').modal('show');

        if (clean) {
            getArticles("", "");
            document.getElementById("option").innerHTML = `<option selected disabled value="0">Opciones</option>`;
            var type = document.getElementById("type").value = 0;
            document.getElementById("currency").style.display = "none";
        }
        else {
            var type = document.getElementById("type").value;
            var param = document.getElementById("option").value;
            getArticles(type, param);
        }
        $('#exampleModal').modal('hide');

    }

        function getArticles(type, param) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetArticles","Home")',
                data: {
                    type: type,
                    param: param
                },
                cache: false
            })
                .then(function (data) {
                    var element = document.getElementById("articleListContainer");
                    element.innerHTML = data;
                })
                .fail(function (data) {
                    alert('No hay caracteristicas que mostrar!');
                })
               return false;
        }


</script>